name: Nx Monorepo CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      # 3️⃣ Cache dependencies + Nx + workspace setup
      - name: Cache deps + Nx cache
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            .nx/cache
            ~/.npm
            nx.json
            package.json
            package-lock.json
          key: ${{ runner.os }}-nx-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nx-

      # 4️⃣ Install dependencies 
      - name: Install dependencies
        run: npm ci --legacy-peer-deps



      # 6️⃣ Install Nx globally
      - name: Install Nx globally
        run: npm install -g nx@latest

      # 7️⃣ Run affected builds
      - name: Run affected builds
        run: nx affected --target=build --parallel --max-parallel=3
